
CREATE TABLE CUSTOMER (
	ID VARCHAR(250) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PASS VARCHAR(50) NOT NULL,
	ROLE VARCHAR(50) NOT NULL,
	constraint pk_ID primary key (ID)
);

INSERT INTO CUSTOMER VALUES (1, 'cassio', '12345', 'admin');

--CREATE TABLE AUTHORITIES (
--	ID VARCHAR(250) NOT NULL,
--	USERNAME VARCHAR(50) NOT NULL,
--	AUTHORITY VARCHAR(50) NOT NULL,
--	constraint pk_ID2 primary key (ID)
--);

--INSERT INTO USERS VALUES ('NULL', 'happy', '12345', '1');
--INSERT INTO AUTHORITIES VALUES ('NULL', 'happy', 'WRITE');

--INSERT INTO USERS (ID,USERNAME,PASSWORD,ENABLE) VALUES ('NULL', 'happy', '12345', '1');
--INSERT INTO AUTHORITIES (ID,USERNAME,AUTHORITY) VALUES ('N', 'happy', 'write');